[package]
name = "mjml-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5.21", features = ["derive"] }
mrml = "3"
serde = { version = "1.0", features = ["derive"] }
